In [1]:
import torch
import numpy as np
torch.manual_seed(1313)

## 基本設定

In [2]:
def describe(x):
    """
    """
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [3]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-4.3521e+25,  4.5888e-41, -4.3612e+25],
        [ 4.5888e-41, -4.3873e+25,  4.5888e-41]])


In [4]:
describe(torch.randn(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.7375, -0.9502, -1.2876],
        [-2.1311, -1.4955,  0.4420]])


In [5]:
describe(torch.zeros(2, 3))  # initialize tensors of ones or zeros.
x = torch.ones(2, 3)  # initialize tensors of ones or zeros.
describe(x)
x.fill_(5)  # change all values by fill_()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [6]:
x = torch.Tensor([[1, 2,],  
                  [2, 4,]])  # initialized from a list of lists
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 2.],
        [2., 4.]])


In [7]:
npy = np.random.rand(2, 3)  #  initialized from numpy matrices
describe(torch.from_numpy(npy))
print(npy.dtype)

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2667, 0.9914, 0.0027],
        [0.8543, 0.4729, 0.4640]], dtype=torch.float64)
float64


## 基本運算

In [8]:
import torch
x = torch.arange(8).view(2, 4)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 4])
Values: 
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [9]:
x = torch.FloatTensor([[1, 2, 3],  
                       [4, 5, 6]])
describe(x)

x = x.long()  # ????
describe(x)

x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.int64)
describe(x)

x = x.float() 
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
describe(torch.add(x, x))  # values of tensor is addable.
describe(x + x)  # and also operate in this way.

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [11]:
x = x.view(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))

Type: torch.FloatTensor
Shape/size: torch.Size([3])
Values: 
tensor([5., 7., 9.])
Type: torch.FloatTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 6., 15.])


In [13]:
describe(x)
describe(torch.transpose(x, 0, 1))  # https://pytorch.org/docs/stable/generated/torch.transpose.html

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [14]:
import torch
x = torch.arange(6).view(2, 3)  # View tensor shares the same underlying data with its base tensor. 
describe(x)
describe(x[:1, :2])  # [rows, cols]
describe(x[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [15]:
indices = torch.LongTensor([0, 2])
print(indices)
describe(torch.index_select(x, dim=1, index=indices))  # We can select a subset of a tensor using the index_select
"""Returns a new tensor 
which indexes the input tensor along dimension dim 
using the entries in index which is a LongTensor."""

tensor([0, 2])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


'Returns a new tensor \nwhich indexes the input tensor along dimension dim \nusing the entries in index which is a LongTensor.'

In [16]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [17]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


In [18]:
x = torch.LongTensor([[1, 2, 3],  
                      [4, 5, 6],
                      [7, 8, 9]])
describe(x)
print(x.dtype)
print(x.numpy().dtype)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
int64


## tensor運算

In [19]:
x = torch.arange(12).view(3, 4)
y = torch.arange(4).view(1, 4)
z = torch.arange(3).view(3, 1)

print(x)
print(y)
print(z)
print(x + y)
print(x + z)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3]])
tensor([[0],
        [1],
        [2]])
tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])
tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])


In [20]:
x = torch.arange(12).view(3, 4)
print(x.shape)

x = x.unsqueeze(dim=1)  # Unsqueeze and squeeze will add and remove 1-dimensions.
print(x.shape)

x = x.squeeze()
print(x.shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


In [21]:
# Indexing, Slicing, Joining and Mutating
x = torch.arange(6).view(2, 3)
print("x: \n", x)
print("---")
print("x[:2, :2]: \n", x[:2, :2])
print("---")
print("x[0][1]: \n", x[0][1])
print("---")
print("Setting [0][1] to be 8")
x[0][1] = 8
print(x)

x: 
 tensor([[0, 1, 2],
        [3, 4, 5]])
---
x[:2, :2]: 
 tensor([[0, 1],
        [3, 4]])
---
x[0][1]: 
 tensor(1)
---
Setting [0][1] to be 8
tensor([[0, 8, 2],
        [3, 4, 5]])


In [22]:
x = torch.arange(6).view(2,3)
describe(x)
describe(torch.cat([x, x], dim=0))  # Concatenates the given sequence of seq tensors in the given dimension.
describe(torch.cat([x, x], dim=1))
describe(torch.stack([x, x]))  # Concatenates a sequence of tensors along a new dimension.

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [23]:
x1 = torch.arange(6).view(2, 3).float()
describe(x1)

x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

describe(torch.mm(x1, x2))  # Matrix multiplication is torch.mm()
print(x1.mm(x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])
tensor([[ 3.,  6.],
        [12., 24.]])


## 梯度計算

In [24]:
x = torch.tensor([[2.0, 3.0]], requires_grad=True)
print("x: \n", x)
print("---")
z = 3 * x
print("z = 3*x: \n", z)
print("---")

loss = z.sum()
print("loss = z.sum(): \n", loss)
print("---")

loss.backward()

print("after loss.backward(), x.grad: \n", x.grad)

x: 
 tensor([[2., 3.]], requires_grad=True)
---
z = 3*x: 
 tensor([[6., 9.]], grad_fn=<MulBackward0>)
---
loss = z.sum(): 
 tensor(15., grad_fn=<SumBackward0>)
---
after loss.backward(), x.grad: 
 tensor([[3., 3.]])


In [25]:
def f(x):
    if (x.data > 0).all():
        return torch.sin(x)
    else:
        return torch.cos(x)

In [26]:
x = torch.tensor([1.0], requires_grad=True)
y = f(x)
y.backward()  # we need to make sure the output is a scalar.
print(x.grad)

tensor([0.5403])


In [27]:
x = torch.tensor([1.0, 0.5], requires_grad=True)
y = f(x)
#y.backward()  # this is meant to break!
y.sum().backward()
print(x.grad)

tensor([0.5403, 0.8776])


In [28]:
def f2(x):
    """This is because we aren't doing the boolean computation and subsequent application
    of cos and sin on an elementwise basis. So, to solve this, it is common to use masking
    """
    mask = torch.gt(x, 0).float()
    return mask * torch.sin(x) + (1 - mask) * torch.cos(x)

x = torch.tensor([1.0, -1], requires_grad=True)
y = f2(x)
y.sum().backward()
print(x.grad)

tensor([0.5403, 0.8415])


In [29]:
def describe_grad(x):
    if x.grad is None:
        print("No gradient information")
    else:
        print("Gradient: \n{}".format(x.grad))
        print("Gradient Function: {}".format(x.grad_fn))

In [30]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
describe_grad(x)
print("--------")

y = (x + 2) * (x + 5) + 3
describe(y)
z = y.mean()
describe(z)
describe_grad(x)
print("--------")
z.backward(create_graph=True, retain_graph=True)
describe_grad(x)
print("--------")

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
No gradient information
--------
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
No gradient information
--------
Gradient: 
tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]], grad_fn=<CloneBackward>)
Gradient Function: None
--------


In [31]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.grad_fn

### PyTorch's operations can seamlessly be used on the GPU or on the CPU.

In [32]:
print(torch.cuda.is_available())

False


In [33]:
x = torch.rand(3,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.1016, 0.6681, 0.6787],
        [0.7607, 0.7132, 0.0050],
        [0.7311, 0.7151, 0.5614]])


In [34]:
# 設定device判斷以利後續operations
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [35]:
x = torch.rand(3, 3).to(device)
describe(x)
print(x.device)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.0083, 0.0466, 0.6295],
        [0.2705, 0.4879, 0.9412],
        [0.6126, 0.1002, 0.5792]])
cpu


In [36]:
# 假設torch.cuda.is_available()是True，需要.to("cpu")
cpu_device = torch.device("cpu")
y = torch.rand(3, 3)
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[0.1918, 1.0001, 0.6681],
        [1.2045, 0.7947, 1.8211],
        [1.3756, 0.7641, 1.3499]])

In [37]:
# 此為GPU矩陣運算的範例
if torch.cuda.is_available(): # only is GPU is available
    a = torch.rand(3,3).to(device='cuda:0') #  CUDA Tensor
    print(a)
    
    b = torch.rand(3,3).cuda()
    print(b)

    print(a + b)

    a = a.cpu() # Error expected
    print(a + b)